### ISSUE TITLE
disable folding

### ISSUE THREAD

**Issue by baibai25** [luisjure/csound-vim#6]
Hi!

I installed csound-vim recentry. It's very nice project but I don't like automatically code folding. Is that possible to disable code folding? Thank you

**Comment by c0r3dump3d** [comment]
Hi, you can disable the folding code commenting the line `set foldmethod=syntax` in file `.vim/bundle/csound/syntax/csound.vim`

**Comment by luisjure** [comment]
Instead of modifying the plugin, I would recommend including this in you .vimrc:

autocmd Syntax csound setlocal foldmethod=manual

If you don't want to loose syntax folding, but just want the folds to be open by default when you open a file, include this instead:

autocmd Syntax csound normal zR

I'm going to document that in the next release, that should appear soon.

**Comment by baibai25** [comment]
Thank you for your reply.
I've added following statement in my vimrc:

`autocmd Syntax csound setlocal foldmethod=manual`

That works! Thank you,  luisjure and c0r3dump3d!
I'm looking forward to the document to be released.
